"""adfixed gameRoom

Revision ID: 5a501ea9987f
Revises: 2c30aff7187a
Create Date: 2023-05-08 17:34:51.689013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a501ea9987f'
down_revision = '2c30aff7187a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game_room')
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('roomID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('ix_settings_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('ix_settings_username', ['username'], unique=False)

    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.alter_column('roomID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    op.create_table('_alembic_tmp_game_room',
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('roomID', sa.INTEGER(), nullable=False),
    sa.Column('roomName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('playerNumber', sa.INTEGER(), nullable=True),
    sa.Column('turnNumber', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
