"""adfixed gameRoom

Revision ID: 73cee0bade59
Revises: 5a501ea9987f
Create Date: 2023-05-08 17:40:30.910612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cee0bade59'
down_revision = '5a501ea9987f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game_room')
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_index('ix_game_room_playerNumber')
        batch_op.drop_index('ix_game_room_roomID')
        batch_op.drop_index('ix_game_room_roomName')
        batch_op.drop_index('ix_game_room_turnNumber')
        batch_op.drop_index('ix_game_room_username')

    op.drop_table('game_room')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('ix_settings_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('ix_settings_username', ['username'], unique=False)

    op.create_table('game_room',
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('roomID', sa.INTEGER(), nullable=True),
    sa.Column('roomName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('playerNumber', sa.INTEGER(), nullable=True),
    sa.Column('turnNumber', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.create_index('ix_game_room_username', ['username'], unique=False)
        batch_op.create_index('ix_game_room_turnNumber', ['turnNumber'], unique=False)
        batch_op.create_index('ix_game_room_roomName', ['roomName'], unique=False)
        batch_op.create_index('ix_game_room_roomID', ['roomID'], unique=False)
        batch_op.create_index('ix_game_room_playerNumber', ['playerNumber'], unique=False)

    op.create_table('_alembic_tmp_game_room',
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('roomID', sa.INTEGER(), nullable=False),
    sa.Column('roomName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('playerNumber', sa.INTEGER(), nullable=True),
    sa.Column('turnNumber', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
