"""added more to GameRoom

Revision ID: 79e22641c202
Revises: d8111797acd0
Create Date: 2023-05-08 17:21:34.468332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e22641c202'
down_revision = 'd8111797acd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roomName', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('playerNumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('turnNumber', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_room_playerNumber'), ['playerNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_room_roomName'), ['roomName'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_room_turnNumber'), ['turnNumber'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_room_turnNumber'))
        batch_op.drop_index(batch_op.f('ix_game_room_roomName'))
        batch_op.drop_index(batch_op.f('ix_game_room_playerNumber'))
        batch_op.drop_column('turnNumber')
        batch_op.drop_column('playerNumber')
        batch_op.drop_column('roomName')

    # ### end Alembic commands ###
