"""adfixed gameRoom

Revision ID: 8a0133145c77
Revises: 73cee0bade59
Create Date: 2023-05-08 17:41:06.057150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0133145c77'
down_revision = '73cee0bade59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_room',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('roomID', sa.Integer(), nullable=False),
    sa.Column('roomName', sa.String(length=30), nullable=True),
    sa.Column('playerNumber', sa.Integer(), nullable=True),
    sa.Column('turnNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('roomID')
    )
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_room_playerNumber'), ['playerNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_room_roomID'), ['roomID'], unique=True)
        batch_op.create_index(batch_op.f('ix_game_room_roomName'), ['roomName'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_room_turnNumber'), ['turnNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_room_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_room_username'))
        batch_op.drop_index(batch_op.f('ix_game_room_turnNumber'))
        batch_op.drop_index(batch_op.f('ix_game_room_roomName'))
        batch_op.drop_index(batch_op.f('ix_game_room_roomID'))
        batch_op.drop_index(batch_op.f('ix_game_room_playerNumber'))

    op.drop_table('game_room')
    # ### end Alembic commands ###
