"""users table

Revision ID: ad5e03f29853
Revises: 9ea1350fba2e
Create Date: 2023-05-12 12:20:04.841463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5e03f29853'
down_revision = '9ea1350fba2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('primaryColor',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('secondaryColor',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('textColor',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('textColor',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('secondaryColor',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('primaryColor',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
